// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgpmZT4M9DZ93dDaY7J1iOBuMMvvDDKMo',
    appId: '1:419177981019:web:a785c9277f8d58c5154b7e',
    messagingSenderId: '419177981019',
    projectId: 'mylab-4680c',
    authDomain: 'mylab-4680c.firebaseapp.com',
    storageBucket: 'mylab-4680c.firebasestorage.app',
    measurementId: 'G-T2DHCLERHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMXzD4z_4orW_gH2Stw7558UB86FYqcwU',
    appId: '1:419177981019:android:7109c2ea1c0f5f00154b7e',
    messagingSenderId: '419177981019',
    projectId: 'mylab-4680c',
    storageBucket: 'mylab-4680c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Gn_sUPO09U_IV-DHKRydbO4Gjgc8SRM',
    appId: '1:419177981019:ios:89a9113b97bda97c154b7e',
    messagingSenderId: '419177981019',
    projectId: 'mylab-4680c',
    storageBucket: 'mylab-4680c.firebasestorage.app',
    iosBundleId: 'com.example.labReport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8Gn_sUPO09U_IV-DHKRydbO4Gjgc8SRM',
    appId: '1:419177981019:ios:89a9113b97bda97c154b7e',
    messagingSenderId: '419177981019',
    projectId: 'mylab-4680c',
    storageBucket: 'mylab-4680c.firebasestorage.app',
    iosBundleId: 'com.example.labReport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgpmZT4M9DZ93dDaY7J1iOBuMMvvDDKMo',
    appId: '1:419177981019:web:b581cceb131abc28154b7e',
    messagingSenderId: '419177981019',
    projectId: 'mylab-4680c',
    authDomain: 'mylab-4680c.firebaseapp.com',
    storageBucket: 'mylab-4680c.firebasestorage.app',
    measurementId: 'G-CVKF4LM3L1',
  );
}
